### ISSUE TITLE
Xilinx tools version?

### ISSUE THREAD

**Issue by smosanu** [enjoy-digital/fk33_hbm2#1]
Would you please also specify the version of the Xilinx Vivado that you used to generate the IP and synthesize the design with? Thank you!

Using 2019.2 I encountered an issue but was able to fix it following the suggestions [here](https://www.xilinx.com/support/answers/72607.html). I added
`connect_debug_port dbg_hub/clk [get_nets apb_clk]` 
to the .xdc file and it fixed the issue, plus am also installing Vivado 2020.1 (the ES1 license is version limited) to be more in step with the times.

**Comment by enjoy-digital** [comment]
@smosanu: This has been tested with Vivado 2018.2 (https://github.com/enjoy-digital/fk33_hbm2/commit/6ebd56331062c2bd6d305c7cebf3147c772cf1b4). If support for newer version of Vivado requires some changes, we could also integrate it (and add a --vivado-version=20xx.x parameter to specify the version). Would you mind sharing the fk33.py that compiles with Vivado 2019.2 and >?

**Comment by smosanu** [comment]
Will gladly share the fk33.py file - I added the line
`self.add_platform_command("connect_debug_port dbg_hub/clk [get_nets apb_clk]")`
and had to remove the `-es1` since my license doesn't cover that for fk33 (feel free to ignore this bit).

I also successfully generated the bitstream for Alveo U280 and programmed it, and will try to interface with it, though am not sure how since I didn't add the UART. Will let you know how it goes.
Edit: Wasn't able to figure out how to use lxterm with jtag crossover uart. :(

**Comment by smosanu** [comment]
Had to switch to using the board serial port for UART since I couldn't figure out how to use the JTAG bridge. After, I was able to boot into LiteX and run mem_list, mem_test and mem_speed just like in your [twitter](https://twitter.com/enjoy_digital/status/1390336281176117249) example. It works!!!

I would like to make a pull request to make the au280 code available next to the fk33, but perhaps you can create an au280 branch so that I don't collude with the master?

**Comment by enjoy-digital** [comment]
Great for the test on the Alveo U280. Even if the repo was for the FK33, we could integrate the U280 support here if you want. In the long term (next weeks/months) we could move HBM2 support directly to LiteX-Boards to simplify things.
